# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set environment variables
#ENV OPENAI_API_KEY = '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'

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 8000

# Run app.py when the container launches
CMD ["uvicorn", "app:app", "--reload", "--port", "8000", "--host", "0.0.0.0"]